# ===================================================================
# Walt — high-energy proton, near-equatorial, relativistic L_eff
# ===================================================================

particle: proton
energy_eV: 1.0e8
pitch_deg: 89.0
phi_deg: 0.0
x_initial: 5.7045989
gyroperiods: 1.0e4
use_gyroradius_L_correction: true

solvers:
  ps: true
  adaptive: true

ps_order: 1000
read_data: false

steps_per_gyro:
  ps: 20
round_steps: false

plotting:
  titles: true
  full_plot: true
  slice_mode: first
  n_gyro: 175

window_time: 5.0

external_h5:
  ps:   "outputs/outputs_rawdata/run_304603211ada647c.h5"
  rk4:  "outputs/outputs_rawdata/run_60a0558ebec9f956.h5"
  rk45: "outputs/outputs_rawdata/run_60a0558ebec9f956.h5"
  rkg:  "outputs/outputs_rawdata/run_60a0558ebec9f956.h5"
