# ===================================================================
# Dragt — high-energy proton with relativistic L_eff
# (energy_eV / pitch_deg / particle inherited from base.yml)
# ===================================================================

pitch_deg: 67.61877044327187
phi_deg: -90.0
x_initial: 4.45978528
energy_eV: 71.37202917184707e6 
gyroperiods: 1.0e4
use_gyroradius_L_correction: false

solvers:
  adaptive: true

ps_order: 1000

plotting:
  titles: true
  slice_mode: first
  gyro_window: first
  n_gyro: 175

window_time: 5.0
