# ===================================================================
# Paper 1 — 100 keV proton, 30° pitch, 5 R_E
# ===================================================================

energy_eV: 100.0e3
pitch_deg: 30.0
phi_deg: 90.0


solvers:
  rk4: true
  rk45: true
  rkg: true

gyroperiods: 1.5e5

window_time: 6209.0

