# ===================================================================
# Walt — high-energy proton, near-equatorial, relativistic L_eff
# ===================================================================

pitch_deg: 89.0
phi_deg: 0.0
x_initial: 5.7045989
gyroperiods: 1.0e4
use_gyroradius_L_correction: true

solvers:
  adaptive: true

ps_order: 1000
read_data: false

steps_per_gyro:
  ps: 20

plotting:
  titles: true
  slice_mode: first
  n_gyro: 175

window_time: 5.0
