import numpy as np
import os
import matplotlib.pyplot as mpl

USE_FLOAT128 = False  # RKG Will be diabled if this is True

if USE_FLOAT128: npfloat = np.float128 
else: npfloat = np.float64

# ===== System Constants =====
q_e = npfloat(-1.602176634e-19)        # C
m_e = npfloat(9.1093837139e-31)        # kg
m_p = npfloat(1.67262192595e-27)       # kg
evtoj = npfloat(1.602176634e-19)       # eV to J
spdlight = npfloat(299792458.0)
RE = npfloat(6378137.0)                # m, Radius of Earth

# ===== Tolerances/Truncations =====
PS_order = 40                       # Max Power Series Order, system will truncate
tol = 1.0 * np.finfo(npfloat).eps   # setting tolerance to machine epsilon to drop terms later, will be multiplied by tau_0
rtol_rk45 = 1e-8                    # RK45 relative tolerance
atol_rk45 = 1e-10                   # RK45 adapative tolerance
user_min_phase = npfloat(1)        # Minimum radians to extrapolate drift from,   .0000001 needed for L=1, 10 eV electron
mpl.rcParams['agg.path.chunksize'] = 100   # may have to adjust if matplotlib barfs on large datasets

if USE_FLOAT128: mpl.rcParams['agg.path.chunksize'] = 100000  
else: mpl.rcParams['agg.path.chunksize'] = 1000


MAX_PLOT_POINTS= 200000 # cap number of points on each graph to speed things up
PS_CHUNKING = True   # for this file, we want streaming mode
PS_chunk_steps = int(1e4)
PS_decimate = 10

run_storage = "outputs_rawdata"       # where raw trajectory files go when USE_WRITE_DATA = True

# ===================================================================
# ==============Toggle Parameters for Dipole Script ================
# ===================================================================
"""
USE_RK45 --  Set to True to include RK45 analysis
USE_RK4 --   Set to True to include RK4 analysis
USE_RKG --   Set to True to include RKG analysis
USE_PS  --   Set to True to include PS analysis
READ_DATA -- Set to True to scan for saved runs and load
WRITE_DATA -- Set to True to write saved run data to hdf file (what READ_DATA looks for)
USE_PLOT_TITLES -- Set to True to include plot titles
USE_FULL_PLOT -- Set False for paper plots only, Set to True for all plots

USE_EXTERNAL_H5_* -- Set to True to load from external h5 file specifically to compare against current run for energy, this is 
                        useful for large runs where multiple parameter sets are being compared and timescales differ
external_h5_* -- path to external h5 file to load from, for PS also need to set PS_order_ext to match order used in that run
                        
pitch_deg -- (degrees)
phi_deg  -- (degrees)
x_initial_si -- (Earth Radius: RE)
y_initial_si -- (RE)
z_initial_si -- (RE)
KE_particle -- (eV)
B_0 -- (T)
mass_si -- m_e or m_p, otherwise manual (kg)
T_gyro -- gyroperiod at initial position (normalized time) 2.0 * np.pi * (L**3) 

window duration -- how much time (in normalized time) you wish to plot for slice visual inspection, generall
                    I taken as one drift period in physical time divided by tau_0 but this requires having already 
                    run the sim to get drift period
slice_mode -- "last" or "first", slices window from beginning or end of simulation               
N_GYRO -- number of gyroperiods to display, recall that the characteristic gyroperiod is defined in terms of equatorial B field
gyro_window -- "first" or "last" or "all", chooses which set of gyroperiods to display within the window
    
integration_steps (N) -- number of steps per characteristic gyroperiod to use to calculate rk4_step and ps_step below
rk4_step -- ~integration points per gyroperiod (2πL^3/N)               
ps_step --  same as rk4_step, set equal for direct time step comparison
rkg_step -- same as rk4_step, set equal for direct time step comparison
gyroperiods -- number of characteristic gyroperiods to run simulation for
norm_time -- this should be some multiple of gyroperiods designed (norm_time/2π = gyroperiods), 
    calculated drift/tau_0 to plot one cycle (you'll need to run once)

The dipole simulations involve long-duration, high-order integrations. For reproducibility, only the primary configurations 
corresponding to the figures in the paper’s main text are included. Appendix-level datasets can be generated by altering the 
parameters below or by adding new run modes. However, the datapoints and scripts are provided in misc_plots/ for reference and use.
"""

def load_params(run):
    if run == "demo": #paper2 simulation at reduced norm time for quick demo
        if USE_FLOAT128: print("Running DEMO simulation in float128...this may take a few minutes\n")
        else: print("Running DEMO simulation...this takes just few seconds\n")
        output_folder = "outputs_demo"
        os.makedirs(output_folder, exist_ok=True)
        USE_RK45 = True  
        USE_RK4 = True
        USE_RKG = False  # does not work for electrons, see paper
        USE_PS = True
        USE_PLOT_TITLES = True
        READ_DATA = True
        WRITE_DATA = True
        USE_FULL_PLOT = False

        USE_EXTERNAL_H5_ps = False
        USE_EXTERNAL_H5_rk4 = False
        USE_EXTERNAL_H5_rk45 = False
        USE_EXTERNAL_H5_rkg = False

        external_h5_ps = "outputs_rawdata/" 
        PS_order_ext = 1    # pull from summary text file 
        external_h5_rk4 = "outputs_rawdata/" 
        external_h5_rk45 = "outputs_rawdata/" 
        external_h5_rkg = "outputs_rawdata/" 


        pitch_deg = npfloat(60.0)              
        phi_deg = npfloat(90.0)
        x_initial = npfloat(5)                 
        y_initial = npfloat(0)
        z_initial = npfloat(0)
        KE_particle = npfloat(100e6) 
        B_0 = npfloat(3.12e-5)  
        mass_si = m_e   
        T_gyro = 2.0 * np.pi * (x_initial**3)  

        window_time = npfloat(11.6) # only interested in one drift period, SI units
        slice_mode = "first"  
        N_GYRO = 75
        gyro_window = "last"            

        N_STEPS_PER_GYRO_rk4= 65
        N_STEPS_PER_GYRO_ps=65
        N_STEPS_PER_GYRO_rkg=65
        rk4_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rk4,1))               
        ps_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_ps,1))                                  
        rkg_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rkg,1))                       
        gyroperiods = 4.1e2
        norm_time = npfloat(gyroperiods) * T_gyro

    elif run == "paper1": #100 keV proton, 30deg pitch, 5RE, B0 at Earth surface
        if USE_FLOAT128: print("Running PAPER simulation in float128...this may take a >30 minutes\n")
        else: print("Running full PAPER simulation...this can take a few minutes\n")
        output_folder = "outputs_paper"
        os.makedirs(output_folder, exist_ok=True)
        USE_RK45 = True  
        USE_RK4 = True  # removed from paper plots due to failure
        USE_RKG = True
        USE_PS = True
        USE_PLOT_TITLES = False
        READ_DATA = True 
        WRITE_DATA = True
        USE_FULL_PLOT = False

        USE_EXTERNAL_H5_ps = False
        USE_EXTERNAL_H5_rk4 = False
        USE_EXTERNAL_H5_rk45 = False
        USE_EXTERNAL_H5_rkg = False

        external_h5_ps = "outputs_rawdata/run_669e61bd5c4a6f40.h5" # big PS run
        PS_order_ext = 16    # old h5 files did not have max_ps captured, new do. Us inspect_hdf5.py to check 
        external_h5_rk4 = "outputs_rawdata/" 
        external_h5_rk45 = "outputs_rawdata/" 
        external_h5_rkg = "outputs_rawdata/run_2710a82210ebb716.h5"

        pitch_deg = npfloat(30.0)              
        phi_deg = npfloat(90.0)
        x_initial = npfloat(5)                 
        y_initial = npfloat(0)
        z_initial = npfloat(0)
        KE_particle = npfloat(100e3)              
        B_0 = npfloat(3.12e-5)  
        mass_si = m_p   
        T_gyro = 2.0 * np.pi * (x_initial**3)  

        window_time = npfloat(6209.0) # only interested in ~one drift period so same as slice
        slice_mode = "last"   
        N_GYRO = 150
        gyro_window = "last"   

        # used for paper only, see "tinker" for better approach
        N_STEPS_PER_GYRO_rk4= 65
        N_STEPS_PER_GYRO_ps=65
        N_STEPS_PER_GYRO_rkg=65
        rk4_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rk4,1))               
        ps_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_ps,1))                                  
        rkg_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rkg,1))  
        totatl_integration_steps = 1e7
        norm_time = npfloat(totatl_integration_steps) * ps_step
        gyroperiods= npfloat(totatl_integration_steps) * ps_step / T_gyro

    elif run == "paper2": #100 MeV electron, 60 degree pitch, 5RE, B0 at Earth surface
        if USE_FLOAT128: print("Running PAPER simulation in float128...this may take a >30 minutes\n")
        else: print("Running full PAPER simulation...this can take a few minutes\n")
        output_folder = "outputs_troubleshoot"
        os.makedirs(output_folder, exist_ok=True)
        USE_RK45 = True  
        USE_RK4 = True
        USE_RKG = False  # does not work for electrons, see paper
        USE_PS = True
        USE_PLOT_TITLES = True
        READ_DATA = True
        WRITE_DATA = True
        USE_FULL_PLOT = False

        USE_EXTERNAL_H5_ps = False
        USE_EXTERNAL_H5_rk4 = False
        USE_EXTERNAL_H5_rk45 = False
        USE_EXTERNAL_H5_rkg = False

        external_h5_ps = "outputs_rawdata/run_5f2698f4194712e0.h5" #big PS run
        PS_order_ext = 1    # pull from text file for old runs, new h5 files should grab it
        external_h5_rk4 = "outputs_rawdata/" 
        external_h5_rk45 = "outputs_rawdata/" 
        external_h5_rkg = "outputs_rawdata/" 


        pitch_deg = npfloat(60.0)              
        phi_deg = npfloat(90.0)
        x_initial = npfloat(5)                 
        y_initial = npfloat(0)
        z_initial = npfloat(0)
        KE_particle = npfloat(100e6) 
        B_0 = npfloat(3.12e-5)  
        mass_si = m_e   
        T_gyro = 2.0 * np.pi * (x_initial**3)  

        window_time = npfloat(11.6) # only interested in one drift period, SI units 
        slice_mode = "last"  
        N_GYRO = 75
        gyro_window = "last"            


        N_STEPS_PER_GYRO_rk4= 65
        N_STEPS_PER_GYRO_ps=65
        N_STEPS_PER_GYRO_rkg=65
        rk4_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rk4,1))               
        ps_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_ps,1))                                  
        rkg_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rkg,1))  
        totatl_integration_steps = 1e7
        norm_time = npfloat(totatl_integration_steps) * ps_step
        gyroperiods= npfloat(totatl_integration_steps) * ps_step / T_gyro

    elif run == "paper3": #paper1 simulation at larger ps_step and smaller rk4_step
        if USE_FLOAT128: print("Running PAPER simulation in float128...this may take a >30 minutes\n")
        else: print("Running full PAPER simulation...this can take a few minutes\n")
        output_folder = "outputs_paper_FIXME"
        os.makedirs(output_folder, exist_ok=True)
        USE_RK45 = False  
        USE_RK4 = True 
        USE_RKG = False  
        USE_PS = True
        USE_PLOT_TITLES = False
        READ_DATA = True
        WRITE_DATA = True
        USE_FULL_PLOT = False

        USE_EXTERNAL_H5_ps = False
        USE_EXTERNAL_H5_rk4 = False
        USE_EXTERNAL_H5_rk45 = False
        USE_EXTERNAL_H5_rkg = False

        external_h5_ps = "outputs_rawdata/" 
        PS_order_ext = 1    
        external_h5_rk4 = "outputs_rawdata/" 
        external_h5_rk45 = "outputs_rawdata/"
        external_h5_rkg = "outputs_rawdata/" 

        pitch_deg = npfloat(30.0)              
        phi_deg = npfloat(90.0)
        x_initial = npfloat(5)                 
        y_initial = npfloat(0)
        z_initial = npfloat(0)
        KE_particle = npfloat(100e3)              
        B_0 = npfloat(3.12e-5)  
        mass_si = m_p   
        T_gyro = 2.0 * np.pi * (x_initial**3)  

        window_time = npfloat(6220.0) # only interested in one drift period so same as slice
        slice_mode = "last"   
        N_GYRO = 150
        gyro_window = "first"   

        rk4_step = npfloat(.5)                
        ps_step = npfloat(78.5)
        PS_order = 30
        rkg_step = rk4_step  # doesn't matter since USE_RKG = False but needs a value for h5 consistency                    
        norm_time = npfloat(6206.0) # only interested in one drift period so same as slice

    elif run == "tinker": # using this one to play with parameters 
        if USE_FLOAT128: print("Running PAPER simulation in float128...this may take a >30 minutes\n")
        else: print("Running full PAPER simulation...this can take a few minutes\n")
        output_folder = "outputs_troubleshoot"
        os.makedirs(output_folder, exist_ok=True)
        USE_RK45 = True  
        USE_RK4 = True
        USE_RKG = True  
        USE_PS = True
        USE_PLOT_TITLES = False
        READ_DATA = False
        WRITE_DATA = True
        USE_FULL_PLOT = True

        pitch_deg = npfloat(30.0)              
        phi_deg = npfloat(90.0)
        x_initial = npfloat(5)                 
        y_initial = npfloat(0)
        z_initial = npfloat(0)
        KE_particle = npfloat(100e3) 
        B_0 = npfloat(3.12e-5)  
        mass_si = m_p  
        T_gyro = 2.0 * np.pi * (x_initial**3)  

        USE_EXTERNAL_H5_ps = False
        USE_EXTERNAL_H5_rk4 = False
        USE_EXTERNAL_H5_rk45 = False
        USE_EXTERNAL_H5_rkg = False

        external_h5_ps = "outputs_rawdata/" 
        PS_order_ext = 1
        external_h5_rk4 = "outputs_rawdata/"
        external_h5_rk45 = "outputs_rawdata/" 
        external_h5_rkg = "outputs_rawdata/" 

        window_time = npfloat(6220.0) # only interested in one drift period so same as slice
        slice_mode = "last"  
        N_GYRO = 150
        gyro_window = "last"            
        
        N_STEPS_PER_GYRO_rk4= 200
        N_STEPS_PER_GYRO_ps=65
        N_STEPS_PER_GYRO_rkg=200
        rk4_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rk4,2)) #if very small may need to increase rounding digit              
        ps_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_ps,2))                                  
        rkg_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rkg,2))                                  
        gyroperiods = 1e3
        norm_time = npfloat(gyroperiods) * T_gyro 

    elif run == "monster_ps": #100 keV proton, 30deg pitch, 5RE, B0 at Earth surface
        if USE_FLOAT128: print("Running PAPER simulation in float128...this may take a >30 minutes\n")
        else: print("Running full PAPER simulation...this can take a few minutes\n")
        output_folder = "outputs_giant_runs"
        os.makedirs(output_folder, exist_ok=True)
        USE_RK45 = False   
        USE_RK4 = False  
        USE_RKG = False
        USE_PS = True
        USE_PLOT_TITLES = True
        READ_DATA = True 
        WRITE_DATA = True
        USE_FULL_PLOT = False

        USE_EXTERNAL_H5_ps = False
        USE_EXTERNAL_H5_rk4 = False
        USE_EXTERNAL_H5_rk45 = False
        USE_EXTERNAL_H5_rkg = False

        external_h5_ps = "outputs_rawdata/" 
        PS_order_ext = 16    
        external_h5_rk4 = "outputs_rawdata/" 
        external_h5_rk45 = "outputs_rawdata/" 
        external_h5_rkg = "outputs_rawdata/" 

        pitch_deg = npfloat(30.0)              
        phi_deg = npfloat(90.0)
        x_initial = npfloat(5)                 
        y_initial = npfloat(0)
        z_initial = npfloat(0)
        KE_particle = npfloat(100e3)              
        B_0 = npfloat(3.12e-5)  
        mass_si = m_p   
        T_gyro = 2.0 * np.pi * (x_initial**3)  

        window_time = npfloat(6209.0) # only interested in one drift period so same as slice
        slice_mode = "last"   
        N_GYRO = 150
        gyro_window = "last"   

        N_STEPS_PER_GYRO_rk4= 65
        N_STEPS_PER_GYRO_ps=65
        N_STEPS_PER_GYRO_rkg=65
        rk4_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rk4,1))               
        ps_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_ps,1))                                  
        rkg_step = npfloat(round(T_gyro/N_STEPS_PER_GYRO_rkg,1))                         
        gyroperiods = 1e7
        norm_time = npfloat(gyroperiods) * T_gyro
    else:
        raise ValueError("run must be 'demo', 'paper1', 'paper2', or 'paper3'")

    return locals()    
